import { Injectable, Logger } from '@nestjs/common';
import { DevFlowStateType, GeneratedArtifact } from '../graph/devflow.state';
import { MemoryService } from '../../memory/memory.service';
import { EventLogService } from '../../supervisor/event-log.service';
import { GraphLlmProvider } from '../providers/graph-llm.provider';

// ─── Constants ────────────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `You are a senior software architect generating comprehensive documentation.
Respond ONLY with a JSON array — no prose, no markdown fences.

Each element: { "filePath": string, "content": string, "language": string }`;

// ─── Node ─────────────────────────────────────────────────────────────────────

@Injectable()
export class ArchitectureAgentNode {
  private readonly logger = new Logger(ArchitectureAgentNode.name);

  constructor(
    private readonly memory: MemoryService,
    private readonly eventLog: EventLogService,
    private readonly graphLlm: GraphLlmProvider,
  ) {}

  async execute(
    state: DevFlowStateType,
  ): Promise<Partial<DevFlowStateType>> {
    this.logger.log(`[${state.projectId}] Architecture agent generating docs`);

    if (!state.contract) {
      return { error: 'ArchitectureAgentNode: contract is null' };
    }

    // Log STARTED — allSettled inside, so failure here does not block the node.
    await this.eventLog.logStarted(state.projectId, 'architecture_agent');

    try {
      // ── 1. Read relevant memories ──────────────────────────────────────────
      // companyName is included so industry-specific architecture patterns
      // (e.g. "fintech microservices complex") rank above generic results.
      const memoryQuery = [
        state.contract.requirements.projectType,
        state.stackKey,
        state.contract.requirements.complexity,
        state.companyName,
      ]
        .filter(Boolean)
        .join(' ');

      const memories = await this.memory.readRelevant('architecture', memoryQuery);
      const memoryContext = this.memory.formatAsContext(memories);
      const docFiles = ['ARCHITECTURE.md', 'API.md', 'DEPLOYMENT.md'];

      // ── 2. Skip-generation check ───────────────────────────────────────────
      // Must run AFTER readRelevant so memory context is still available if the
      // skip threshold is not met. Returns immediately — no LLM tokens consumed.
      const skipCandidate = await this.memory.findSkipCandidate(
        'architecture',
        memoryQuery,
        state.stackKey,
      );

      if (skipCandidate) {
        this.logger.log(
          `[${state.projectId}] Skip-generation: reusing architecture memory artifact (similarity=${skipCandidate.similarity?.toFixed(3)})`,
        );
        const rememberedFilePath = skipCandidate.metadata['filePath'];
        const artifact: GeneratedArtifact = {
          agentType: 'architecture',
          filePath:
            typeof rememberedFilePath === 'string'
              ? rememberedFilePath
              : 'ARCHITECTURE.md',
          content: skipCandidate.content,
          language: 'markdown',
        };
        return { artifacts: this.completeArtifacts(docFiles, [artifact], state) };
      }

      // ── 3. Summarise generated artifacts ──────────────────────────────────
      const artifactSummary = state.artifacts
        .map((a) => `${a.agentType}: ${a.filePath}`)
        .join('\n');

      if (process.env.MOCK_MODE === 'true') {
        const artifacts = this.completeArtifacts(
          docFiles,
          [
            {
              agentType: 'architecture',
              filePath: 'ARCHITECTURE.md',
              content: `# Mock Architecture\n\nGenerated by Mock Mode.`,
              language: 'markdown'
            }
          ],
          state,
        );
        await this.eventLog.logCompleted(state.projectId, 'architecture_agent', { inputTokens: 0, outputTokens: 0, model: 'mock' });
        return { artifacts };
      }

      // ── 4. LLM call ───────────────────────────────────────────────────────
      const result = await this.graphLlm.generateJson<Array<{
        filePath: string;
        content: string;
        language?: string;
      }>>({
        agentName: 'architecture_agent',
        systemPrompt: memoryContext
          ? `${SYSTEM_PROMPT}\n\nRelevant memory:\n${memoryContext}`
          : SYSTEM_PROMPT,
        userPrompt: `Generate architecture documentation for this project:

Project: ${state.contract.projectName}
Description: ${state.contract.description}
Tech Stack: ${JSON.stringify(state.contract.requirements.techStack, null, 2)}
Features: ${state.contract.requirements.features.join(', ')}
Acceptance Criteria: ${state.contract.acceptanceCriteria.join('; ')}

Already generated files:
${artifactSummary}

Generate these 3 documentation files:

1. ARCHITECTURE.md
   - System overview
   - Mermaid diagram (graph TD) showing the main components and data flow
   - Component descriptions
   - Design decisions and trade-offs

2. API.md
   - OpenAPI-style documentation for all endpoints
   - Request/response schemas
   - Authentication details
   - Error codes

3. DEPLOYMENT.md
   - Prerequisites
   - Environment variable reference
   - Docker setup instructions
   - Production deployment checklist
   - Health check endpoints`,
        expectedShape: 'array',
        maxTokens: 6144,
      });

      const artifacts = this.completeArtifacts(
        docFiles,
        result.value.map((item) => ({
          agentType: 'architecture' as const,
          filePath: item.filePath,
          content: item.content,
          language: item.language ?? 'markdown',
        })),
        state,
      );

      this.logger.log(
        `[${state.projectId}] Architecture agent generated ${artifacts.length} docs (${memories.length} memories injected)`,
      );

      // Log COMPLETED — model field drives cost attribution in RunSupervisorService.
      await this.eventLog.logCompleted(state.projectId, 'architecture_agent', {
        inputTokens: result.usage.inputTokens,
        outputTokens: result.usage.outputTokens,
        model: result.model,
      });

      return { artifacts };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      this.logger.error(`[${state.projectId}] Architecture agent failed: ${message}`);
      return { error: `ArchitectureAgentNode failed: ${message}` };
    }
  }

  private completeArtifacts(
    requestedFiles: string[],
    generated: GeneratedArtifact[],
    state: DevFlowStateType,
  ): GeneratedArtifact[] {
    const byPath = new Map(generated.map((artifact) => [artifact.filePath, artifact]));

    return requestedFiles.map((filePath) => {
      const artifact = byPath.get(filePath);
      if (artifact?.content?.trim()) return artifact;

      return {
        agentType: 'architecture' as const,
        filePath,
        content: this.fallbackContent(filePath, state),
        language: 'markdown',
      };
    });
  }

  private fallbackContent(filePath: string, state: DevFlowStateType): string {
    const projectName = state.contract?.projectName ?? state.companyName;
    const description = state.contract?.description ?? state.brief;

    if (filePath === 'API.md') {
      return `# API

## Overview

${projectName} exposes REST endpoints for health checks and task management.

## Endpoints

### GET /health

Returns service health.

### GET /tasks

Returns task records.

### POST /tasks

Creates a task from a JSON body with a title and optional description.

## Errors

Errors use standard HTTP status codes with a JSON message body.
`;
    }

    if (filePath === 'DEPLOYMENT.md') {
      return `# Deployment

## Prerequisites

- Node.js runtime
- PostgreSQL database
- Environment variables for database and application configuration

## Steps

1. Install dependencies.
2. Run database migrations.
3. Build the frontend and backend.
4. Start the production server.

## Health Check

Use \`GET /health\` after deployment.
`;
    }

    return `# Architecture

## System Overview

${projectName} is generated from this brief: ${description}

## Components

- Next.js frontend for the user interface.
- NestJS backend for application APIs.
- Prisma and PostgreSQL for persistence.

## Flow

\`\`\`mermaid
graph TD
  User[User] --> Web[Next.js Frontend]
  Web --> Api[NestJS API]
  Api --> Db[(PostgreSQL)]
\`\`\`

## Decisions

The generated architecture keeps frontend, backend, and database responsibilities separate so each area can be developed independently.
`;
  }
}
