import { Injectable, Logger } from '@nestjs/common';
import Anthropic from '@anthropic-ai/sdk';
import { DevFlowStateType, GeneratedArtifact } from '../graph/devflow.state';
import { MemoryService } from '../../memory/memory.service';
import { EventLogService } from '../../supervisor/event-log.service';

// ─── Constants ────────────────────────────────────────────────────────────────

/**
 * Architecture agent uses claude-sonnet-4-6 (Phase 2D model tiering decision).
 * Rationale: ARCHITECTURE.md, API.md, and DEPLOYMENT.md are the primary
 * deliverables reviewed by capstone panel evaluators. Higher reasoning quality
 * produces more accurate Mermaid diagrams, OpenAPI schemas, and deployment
 * runbooks. Code generation nodes (frontend/backend/database) stay on haiku
 * because their outputs are validated structurally, not by human judgment.
 */
const ARCHITECTURE_MODEL = 'claude-sonnet-4-6';

const SYSTEM_PROMPT = `You are a senior software architect generating comprehensive documentation.
Respond ONLY with a JSON array — no prose, no markdown fences.

Each element: { "filePath": string, "content": string, "language": string }`;

// ─── Node ─────────────────────────────────────────────────────────────────────

@Injectable()
export class ArchitectureAgentNode {
  private readonly logger = new Logger(ArchitectureAgentNode.name);
  private readonly anthropic = new Anthropic();

  constructor(
    private readonly memory: MemoryService,
    private readonly eventLog: EventLogService,
  ) {}

  async execute(
    state: DevFlowStateType,
  ): Promise<Partial<DevFlowStateType>> {
    this.logger.log(`[${state.projectId}] Architecture agent generating docs`);

    if (!state.contract) {
      return { error: 'ArchitectureAgentNode: contract is null' };
    }

    // Log STARTED — allSettled inside, so failure here does not block the node.
    await this.eventLog.logStarted(state.projectId, 'architecture_agent');

    try {
      // ── 1. Read relevant memories ──────────────────────────────────────────
      // companyName is included so industry-specific architecture patterns
      // (e.g. "fintech microservices complex") rank above generic results.
      const memoryQuery = [
        state.contract.requirements.projectType,
        state.stackKey,
        state.contract.requirements.complexity,
        state.companyName,
      ]
        .filter(Boolean)
        .join(' ');

      const memories = await this.memory.readRelevant('architecture', memoryQuery);
      const memoryContext = this.memory.formatAsContext(memories);

      // ── 2. Skip-generation check ───────────────────────────────────────────
      // Must run AFTER readRelevant so memory context is still available if the
      // skip threshold is not met. Returns immediately — no LLM tokens consumed.
      const skipCandidate = await this.memory.findSkipCandidate(
        'architecture',
        memoryQuery,
        state.stackKey,
      );

      if (skipCandidate) {
        this.logger.log(
          `[${state.projectId}] Skip-generation: reusing architecture memory artifact (similarity=${skipCandidate.similarity?.toFixed(3)})`,
        );
        const rememberedFilePath = skipCandidate.metadata['filePath'];
        const artifact: GeneratedArtifact = {
          agentType: 'architecture',
          filePath:
            typeof rememberedFilePath === 'string'
              ? rememberedFilePath
              : 'ARCHITECTURE.md',
          content: skipCandidate.content,
          language: 'markdown',
        };
        return { artifacts: [artifact] };
      }

      // ── 3. Summarise generated artifacts ──────────────────────────────────
      const artifactSummary = state.artifacts
        .map((a) => `${a.agentType}: ${a.filePath}`)
        .join('\n');

      if (process.env.MOCK_MODE === 'true') {
        const artifacts: GeneratedArtifact[] = [
          {
            agentType: 'architecture',
            filePath: 'ARCHITECTURE.md',
            content: `# Mock Architecture\n\nGenerated by Mock Mode.`,
            language: 'markdown'
          }
        ];
        await this.eventLog.logCompleted(state.projectId, 'architecture_agent', { inputTokens: 0, outputTokens: 0, model: 'mock' });
        return { artifacts };
      }

      // ── 4. LLM call with prompt caching ───────────────────────────────────
      const response = await this.anthropic.messages.create({
        model: ARCHITECTURE_MODEL,
        max_tokens: 6144,
        system: memoryContext
          ? `${SYSTEM_PROMPT}\n\nRelevant memory:\n${memoryContext}`
          : SYSTEM_PROMPT,
        messages: [
          {
            role: 'user',
            content: `Generate architecture documentation for this project:

Project: ${state.contract.projectName}
Description: ${state.contract.description}
Tech Stack: ${JSON.stringify(state.contract.requirements.techStack, null, 2)}
Features: ${state.contract.requirements.features.join(', ')}
Acceptance Criteria: ${state.contract.acceptanceCriteria.join('; ')}

Already generated files:
${artifactSummary}

Generate these 3 documentation files:

1. ARCHITECTURE.md
   - System overview
   - Mermaid diagram (graph TD) showing the main components and data flow
   - Component descriptions
   - Design decisions and trade-offs

2. API.md
   - OpenAPI-style documentation for all endpoints
   - Request/response schemas
   - Authentication details
   - Error codes

3. DEPLOYMENT.md
   - Prerequisites
   - Environment variable reference
   - Docker setup instructions
   - Production deployment checklist
   - Health check endpoints`,
          },
        ],
      });

      // ── 5. Parse ───────────────────────────────────────────────────────────
      const rawContent = response.content[0];
      if (rawContent.type !== 'text') {
        throw new Error('Unexpected response type from Anthropic API');
      }

      const jsonText = rawContent.text
        .replace(/^```(?:json)?\s*/i, '')
        .replace(/\s*```\s*$/, '')
        .trim();

      const parsed = JSON.parse(jsonText) as Array<{
        filePath: string;
        content: string;
        language: string;
      }>;

      const artifacts: GeneratedArtifact[] = parsed.map((item) => ({
        agentType: 'architecture' as const,
        filePath: item.filePath,
        content: item.content,
        language: item.language ?? 'markdown',
      }));

      this.logger.log(
        `[${state.projectId}] Architecture agent generated ${artifacts.length} docs (${memories.length} memories injected)`,
      );

      // Log COMPLETED — model field drives cost attribution in RunSupervisorService.
      const usage = response.usage;
      await this.eventLog.logCompleted(state.projectId, 'architecture_agent', {
        inputTokens: usage.input_tokens,
        outputTokens: usage.output_tokens,
        model: ARCHITECTURE_MODEL, // claude-sonnet-4-6 per Phase 2D tiering
      });

      return { artifacts };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      this.logger.error(`[${state.projectId}] Architecture agent failed: ${message}`);
      return { error: `ArchitectureAgentNode failed: ${message}` };
    }
  }
}
